# Generated by Django 3.2.6 on 2023-01-12 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('para1', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para2', models.TextField(blank=True)),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para3', models.TextField(blank=True)),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para4', models.TextField(blank=True)),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para5', models.TextField(blank=True)),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para6', models.TextField(blank=True)),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para7', models.TextField(blank=True)),
                ('photo7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para8', models.TextField(blank=True)),
                ('photo8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para9', models.TextField(blank=True)),
                ('photo9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('para10', models.TextField(blank=True)),
                ('photo10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
