# Generated by Django 3.2.6 on 2023-01-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDRF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255)),
                ('number_of_objects', models.IntegerField()),
            ],
        ),
    ]
